<?php
return [
    'adminEmail' => env('ADMIN_MAIL'),
    'fileUploadSize' =>[
        'imageFileSize' => 5*1024*1024, // 2 MB
        'imageSizeMsg' => 'Maximum file size is 2 MB',
        'billSize' => 8*1024*1024, // 8 MB
        'billSizeMsg' =>  'File size cannot exceed 8 MB '
    ],
    'fileUploadPath' => [   
            'billUploadFilePath' => '/runtime/bills/',
    ],
    'ajaxUrl' => [
        'institution-deactivate-Url' => 'institution/deactivate',
        'institution-activate-Url' => 'institution/activate',
        'getSelectedRoleCategory-Url' => 'rbac/get-selected-role-categories',
        'getSelectedRoles-url' => 'rbac/get-selected-roles',
        'getAccountDepDropUrl' => 'account/dep-drop',
        'admin-deactivation-Url' => 'account/deactivate',
        'admin-activation-Url' => 'account/activate',
		'dependant-edit-url' => 'member/edit-dependant',
    	'dependant-delete-url' => 'member/delete-dependant',
    	'store-pending-details' =>'member/store-pending-details',	
    	'sotre-depentdant-url'	=> 'member/store-dependant-details',
    	'generate-member-url'	=> 'member/generate-member-url',
    	'get-member-profile-url'	=> 'member/get-member-profile-url',
    	'sent-genarated-link'   => 'member/send-generatedlink',	
    	'remove-spouse' => "member/remove-spouse",	
    	'remove-member' =>"member/remove-primary-member",
    	'delete-member' =>"member/delete",
	    'admin-title-activation-Url' =>'title/activate/',
        'admin-title-deactivation-Url' =>'title/deactivate/',
        'admin-view-conversation-Url' =>'conversations/view-conversations',
        'admin-delete-affiliated-institution-Url' => 'affiliatedinstitution/delete',
        'admin-get-countryCode-Url'=> 'affiliatedinstitution/get-country-code',
        'admin-available-unavailable-Url' => 'restaurant/activate-deactivate-food-item',
        'admin-property-categories-Url' => 'restaurant/property-categories-by-institution',
        'admin-save-category-Url' => 'restaurant/save-property-category',
        'admin-available-unavailable-category-Url' => 'restaurant/activate-deactivate-category-item',
		'dashboard-item-url' => 'institution/create-dashboard-item',       
        'admin-save-committee-type-Url' => 'committee/save-committee-type',
        'admin-activate-deactivate-committee-type-Url' => 'committee/activate-deactivate-committee-type',
        'admin-get-committee-type-Url' => 'committee/get-committee-type',
        'admin-get-committee-type-list-Url' => 'committee/get-committee-type-list',
        'admin-update-committee-type-order-Url'	=> 'committee/update-committee-type-order',
        'admin-save-committee-designation-Url' => 'committee/save-committee-designation',
        'admin-get-committee-designation-Url' => 'committee/get-committee-designation',
        'admin-update-committee-designation-order-Url' => 'committee/update-committee-designation-order',
        'admin-save-committee-period-Url' => 'committee/save-committee-period',
        'admin-get-committee-period-Url' => 'committee/get-committee-period',
        'admin-activate-deactivate-committee-period-Url' => 'committee/activate-deactivate-committee-period',
        'admin-get-period-by-type-Url' => 'committee/get-committee-period-by-type',
        'admin-get-committee-members-Url' => 'committee/get-committee-members',
        'admin-get-committee-member-details-Url' => 'committee/get-committee-member-details',
        'admin-save-committee-member-Url' => 'save-committee-member',
        'admin-delete-committee-member-Url' => 'committee/delete-committee-member',
        'admin-get-member-for-search-Url' => 'committee/get-member-for-search',
        'auto-country-code' => 'institution/get-auto-country-code',
    	'event-id-url' => 'album/create',
    	'delete-album' => 'album/delete',
    	'delete-image' => 'album/delete-image',
    	'change-caption' => 'change-caption',
    	'approve-album' => 'album/approve-album',
    	'reject-order' => 'orders/reject-order',
    	'update-status' => 'orders/update-status',
        'member-role-dep-drop-Url' => 'member/role-dep-drop' ,
        'event-delete-url' =>  'event/delete',
        'news-delete-url' =>  'news/delete',
        'member-data-url' => 'member/member-data-for-editor',
        'remove-member-pic'=>'member/remove-member-pic',
        'remove-member-spousepic'=>'member/remove-spousepic',
    ],
    'constants' =>[
        'restaurant' => 1
    ],
    'enableErrorMailService' => true,
    'errorFromMail' => env('ERROR_FROM_MAIL'),
    'errorToMail' => env('ERROR_TO_MAIL'),
    'errorCcEmail' => env('ERROR_CC_MAIL'),
    'paginationListPageSize' => 15,
    'uploadImageExtenstions' => '.png,.jpg,.gif',
    'uploadImageExtenstionsForNote' => 'In PNG, JPG or GIF formats',
    'appMessages'=>[
        'sessionExpired' => Yii::t('app','Session Expired! Please login to continue'),              
        'permissionDenied' => Yii::t('app','permission Denied'), 
    ],
    'axisPMD' => [
        "AIB" => "Axis bank net banking.",
        "CD" => "Debit/Credit Card.",
        "OIB" => "Other net banking.",
        "NR" => "Neft/Rtgs",
        "CAX" => "Corporate Axis Internet Banking",
        "C" => "Cash",
        "Q" => "Cheque",
        "T" => "Axis Cheque",
        "UPI" => "UPI",
    ]
];
